from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Text, JSON, Date
from sqlalchemy.sql import func
from app.core.database import Base


class OrganizationDetails(Base):
    __tablename__ = "organization_details"

    id = Column(Integer, primary_key=True)
    organization_id = Column(Integer, ForeignKey("organization.id", ondelete="CASCADE"), nullable=False, index=True)
    organization_name = Column(String(255), nullable=True)
    country = Column(String(100), nullable=True)
    industry_type = Column(String(100), nullable=True)
    subscription_plan = Column(String(100), nullable=True)
    governance_hierarchy = Column(String(255), nullable=True)
    knowledgebase_data_upload = Column(String(255), nullable=True)
    certifications = Column(JSON(), nullable=True)
    active_modules = Column(JSON(), nullable=True)
    sites = Column(Integer, nullable=True)
    zones = Column(Integer, nullable=True)
    total_active_workers = Column(Integer, nullable=True)
    admin_count = Column(Integer, nullable=True)
    site_engineers = Column(Integer, nullable=True)
    site_inspectors = Column(Integer, nullable=True)
    workers = Column(Integer, nullable=True)
    contractors = Column(Integer, nullable=True)
    shift_pattern = Column(String(100), nullable=True)
    high_risk_work_categories = Column(JSON(), nullable=True)
    permit_to_work = Column(Boolean(), nullable=True)
    daily_toolbox_talk = Column(Boolean(), nullable=True)
    onsite_clinic = Column(Boolean(), nullable=True)
    incident_frequency_rate = Column(String(50), nullable=True)
    last_audit_date = Column(Date(), nullable=True)
    evacuation_drill_cadence = Column(String(100), nullable=True)
    emergency_contact_name = Column(String(255), nullable=True)
    emergency_contact_phone = Column(String(50), nullable=True)
    primary_admin_name = Column(String(255), nullable=True)
    admin_email = Column(String(255), nullable=True)
    admin_phone = Column(String(50), nullable=True)
    admin_designation = Column(String(100), nullable=True)
    target_go_live_date = Column(Date(), nullable=True)
    integration_needs = Column(String(255), nullable=True)
    training_plan = Column(Text(), nullable=True)
    additional_notes = Column(Text(), nullable=True)
    logo_url = Column(String(512), nullable=True)
    plan_kpi_limit = Column(String(50), nullable=True)
    kpi_selection = Column(String(255), nullable=True)
    custom_kpi = Column(String(255), nullable=True)
    critical_action_closure_sla_hours = Column(Integer, nullable=True)
    standard_action_closure_sla_hours = Column(Integer, nullable=True)
    kpi_reporting_cadence = Column(String(100), nullable=True)
    data_use_confirmed = Column(Boolean(), nullable=True, default=False)
    leadership_approved = Column(Boolean(), nullable=True, default=False)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    updated_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now())
    created_by = Column(Integer, nullable=True)
    updated_by = Column(Integer, nullable=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
