from fastapi import APIRouter

from app.api.v1.route_factory import register_catalog_routes

router = APIRouter()

ENDPOINTS = [
    ("GET", "/dashboards/executive-safety", "dashboard_executive_safety", "Executive safety dashboard"),
    ("GET", "/dashboards/site-command", "dashboard_site_command", "Site command dashboard"),
    ("GET", "/dashboards/my-tasks", "dashboard_my_tasks", "My tasks dashboard"),
    ("GET", "/dashboards/training-compliance", "dashboard_training_compliance", "Training dashboard"),
    ("GET", "/dashboards/vendor-compliance", "dashboard_vendor_compliance", "Vendor dashboard"),
    ("GET", "/dashboards/asset-compliance", "dashboard_asset_compliance", "Asset dashboard"),
    ("GET", "/dashboards/audit-capa", "dashboard_audit_capa", "Audit and CAPA dashboard"),
    ("GET", "/dashboards/risk-register", "dashboard_risk_register", "Risk dashboard"),
    ("GET", "/dashboards/permit-live-board", "dashboard_permit_live_board", "Permit live board"),
    ("GET", "/dashboards/incident-analytics", "dashboard_incident_analytics", "Incident analytics"),
    ("GET", "/dashboards/knowledge-usage", "dashboard_knowledge_usage", "Knowledge usage"),
    ("GET", "/dashboards/ai-intelligence", "dashboard_ai_intelligence", "AI intelligence"),
    ("GET", "/dashboards/data-quality", "dashboard_data_quality", "Data quality"),
    ("GET", "/employees", "employees_list", "List employees"),
    ("POST", "/employees", "employees_create", "Create employee"),
    ("GET", "/employees/{employeeId}", "employees_get", "Get employee"),
    ("PATCH", "/employees/{employeeId}", "employees_update", "Update employee"),
    ("GET", "/employees/{employeeId}/certifications", "employee_certifications_list", "List certifications"),
    ("POST", "/employees/{employeeId}/certifications", "employee_certifications_create", "Add certification"),
    ("GET", "/training/matrix", "training_matrix_get", "Get training matrix"),
    ("PUT", "/training/matrix/{roleId}", "training_matrix_update", "Update training matrix"),
    ("POST", "/training/completions", "training_completions_create", "Record training completion"),
    ("GET", "/training/gaps", "training_gaps_list", "List training gaps"),
    ("GET", "/vendors", "vendors_list", "List vendors"),
    ("POST", "/vendors", "vendors_create", "Create vendor"),
    ("GET", "/vendors/{vendorId}", "vendors_get", "Get vendor"),
    ("PATCH", "/vendors/{vendorId}", "vendors_update", "Update vendor"),
    ("POST", "/vendors/{vendorId}/documents", "vendor_documents_upload", "Upload vendor document"),
    ("POST", "/vendors/{vendorId}/documents/{documentId}/review", "vendor_documents_review", "Review vendor document"),
    ("GET", "/vendor-standards", "vendor_standards_list", "List vendor standards"),
    ("POST", "/vendor-standards", "vendor_standards_create", "Create vendor standard"),
    ("GET", "/vendors/{vendorId}/history", "vendor_history", "Vendor compliance history"),
    ("GET", "/vendor-compliance", "vendor_compliance_list", "List vendor compliance by domain"),
    ("POST", "/vendors/{vendorId}/compliance", "vendor_compliance_save", "Save vendor compliance scores"),
    ("GET", "/vendor-certifications", "vendor_certifications_list", "List all vendor certifications"),
    ("POST", "/vendors/{vendorId}/certifications", "vendor_certification_add", "Add vendor certification"),
    ("GET", "/vendor-risk-scores", "vendor_risk_scores_list", "List vendor risk scores"),
    ("GET", "/assets", "assets_list", "List assets"),
    ("POST", "/assets", "assets_create", "Register asset"),
    ("GET", "/assets/{assetId}", "assets_get", "Get asset"),
    ("PATCH", "/assets/{assetId}", "assets_update", "Update asset"),
    ("GET", "/assets/{assetId}/inspections", "asset_inspections_list", "Inspection history"),
    ("POST", "/assets/{assetId}/inspections", "asset_inspections_create", "Record inspection"),
    ("GET", "/asset-categories", "asset_categories_list", "List asset categories"),
    ("GET", "/asset-maintenance-logs", "asset_maintenance_logs_list", "List all maintenance logs"),
    ("POST", "/assets/{assetId}/maintenance-logs", "asset_maintenance_log_create", "Create maintenance log"),
    ("GET", "/asset-inspections", "asset_inspections_all_list", "List all inspections"),
    ("GET", "/asset-risk-mapping", "asset_risk_mapping_list", "Asset risk mapping"),
    ("GET", "/asset-compliance-rules", "asset_compliance_rules_list", "List asset rules"),
    ("PUT", "/asset-compliance-rules/{ruleId}", "asset_compliance_rules_update", "Update asset rule"),
    ("GET", "/permits", "permits_list", "List permits"),
    ("POST", "/permits", "permits_create", "Create permit"),
    ("GET", "/permits/{permitId}", "permits_get", "Get permit"),
    ("PATCH", "/permits/{permitId}", "permits_update", "Update permit"),
    ("POST", "/permits/{permitId}/submit", "permits_submit", "Submit permit"),
    ("POST", "/permits/{permitId}/approve", "permits_approve", "Approve permit"),
    ("POST", "/permits/{permitId}/reject", "permits_reject", "Reject permit"),
    ("GET", "/permits/{permitId}/conflicts", "permits_conflicts", "Check permit conflicts"),
    ("POST", "/permits/{permitId}/override-conflict", "permits_override_conflict", "Override permit conflict"),
    ("POST", "/permits/{permitId}/extend", "permits_extend", "Extend permit"),
    ("POST", "/permits/{permitId}/close", "permits_close", "Close permit"),
    ("GET", "/permits/{permitId}/audit-trail", "permits_audit_trail", "Permit audit trail"),
    ("GET", "/audit-checklists", "audit_checklists_list", "List audit checklists"),
    ("POST", "/audit-checklists", "audit_checklists_create", "Create audit checklist"),
    ("POST", "/audit-checklists/{checklistId}/publish", "audit_checklists_publish", "Publish checklist"),
    ("POST", "/audits", "audits_create", "Create audit execution"),
    ("GET", "/audits/{auditId}", "audits_get", "Get audit"),
    ("POST", "/audits/{auditId}/findings", "audit_findings_create", "Create audit finding"),
    ("GET", "/capas", "capas_list", "List CAPAs"),
    ("POST", "/capas/{capaId}/submit-closure", "capas_submit_closure", "Submit CAPA closure"),
    ("POST", "/capas/{capaId}/approve-closure", "capas_approve_closure", "Approve CAPA closure"),
    ("GET", "/risks/assessments", "risk_assessments_list", "List risk assessments"),
    ("POST", "/risks/assessments", "risk_assessments_create", "Create risk assessment"),
    ("GET", "/hazards", "hazards_list", "List hazards"),
    ("GET", "/incidents", "incidents_list", "List incidents"),
    ("POST", "/incidents/{incidentId}/classify", "incidents_classify", "Classify incident"),
    ("POST", "/incidents/{incidentId}/investigations", "incident_investigations_create", "Start investigation"),
    ("POST", "/reports/permits/export", "reports_permits_export", "Export permits"),
    ("POST", "/reports/audits/export", "reports_audits_export", "Export audits"),
    ("POST", "/reports/capas/export", "reports_capas_export", "Export CAPAs"),
    ("POST", "/reports/incidents/export", "reports_incidents_export", "Export incidents"),
    ("POST", "/reports/vendors/export", "reports_vendors_export", "Export vendors"),
    ("POST", "/reports/assets/export", "reports_assets_export", "Export assets"),
    ("POST", "/reports/training/export", "reports_training_export", "Export training"),
]

register_catalog_routes(router, "web", ENDPOINTS)
