import { auth } from '../config/firebase';

const API_BASE_URL = (import.meta.env.VITE_API_URL || '/api').replace(/\/$/, '');

export interface ChatMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

type AiChatResponse = {
  answer?: string;
  content?: string;
  error?: string;
};

async function getAuthHeaders(): Promise<HeadersInit> {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };

  try {
    const token = await auth.currentUser?.getIdToken();
    if (token) headers.Authorization = `Bearer ${token}`;
  } catch (error) {
    console.warn('Unable to resolve Firebase token for AI request:', error);
  }

  try {
    const storedUserRaw = localStorage.getItem('hse_user');
    if (storedUserRaw) {
      const storedUser = JSON.parse(storedUserRaw);
      if (storedUser?.email) headers['X-User-Email'] = storedUser.email;
      if (storedUser?.role) headers['X-User-Role'] = storedUser.role;
    }
  } catch {
    // no-op
  }

  return headers;
}

function extractAssistantText(payload: AiChatResponse): string {
  const value = payload.answer ?? payload.content;
  return typeof value === 'string' && value.trim().length > 0
    ? value
    : 'No response generated by AI service.';
}

export async function sendChatMessage(messages: ChatMessage[]): Promise<string> {
  const headers = await getAuthHeaders();
  const response = await fetch(`${API_BASE_URL}/ai/chat`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ messages }),
  });

  const data = (await response.json().catch(() => ({}))) as AiChatResponse;

  if (!response.ok) {
    const reason = data.error || response.statusText || 'AI request failed';
    throw new Error(reason);
  }

  return extractAssistantText(data);
}

export async function chatWithAIAgent(
  userMessage: string,
  conversationHistory: ChatMessage[] = [],
): Promise<string> {
  const systemPrompt = [
    'You are an HSE (Health, Safety, and Environment) intelligence assistant.',
    'Provide concise, practical, and action-oriented responses.',
    'Use markdown formatting for readability (headings, bullets, short tables where useful).',
  ].join(' ');

  const messages: ChatMessage[] = [
    { role: 'system', content: systemPrompt },
    ...conversationHistory,
    { role: 'user', content: userMessage },
  ];

  return sendChatMessage(messages);
}

export async function analyzeViolations(violationData: unknown): Promise<string> {
  const prompt = `Analyze the following violation dataset and return: key trends, high-risk areas, and top recommendations.\n\nData:\n${JSON.stringify(violationData, null, 2)}`;
  return chatWithAIAgent(prompt);
}

export async function getPredictedRisks(historicalData: unknown): Promise<string> {
  const prompt = `Based on this historical data, provide a risk forecast with probability and preventive actions.\n\nData:\n${JSON.stringify(historicalData, null, 2)}`;
  return chatWithAIAgent(prompt);
}

export async function generateRecommendations(context: string): Promise<string> {
  return chatWithAIAgent(`Generate prioritized HSE recommendations from this context:\n\n${context}`);
}

export async function analyzeZoneRisks(zoneData: unknown): Promise<string> {
  const prompt = `Assess zone-level risk from the dataset and recommend controls by priority.\n\nData:\n${JSON.stringify(zoneData, null, 2)}`;
  return chatWithAIAgent(prompt);
}

export default {
  sendChatMessage,
  chatWithAIAgent,
  analyzeViolations,
  getPredictedRisks,
  generateRecommendations,
  analyzeZoneRisks,
};
